# Generated by Django 3.0.6 on 2020-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartprofile', '0005_auto_20200519_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='GPS_Accuracy',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='GPS_Altitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='GPS_Latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='GPS_Longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
