# Generated by Django 3.0.6 on 2020-05-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartprofile', '0006_auto_20200519_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='SubmissionDate',
        ),
        migrations.RemoveField(
            model_name='household',
            name='end',
        ),
        migrations.RemoveField(
            model_name='household',
            name='start',
        ),
    ]
