# Generated by Django 3.0.6 on 2020-05-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartprofile', '0007_auto_20200519_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='SubmissionDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
